/**
 * Ask the live adjudicator which missing pairs it thinks are real.
 *
 * Leo: "when i click why not for some combinations it says actually this
 * combination does exist." That is the design working as intended — the model
 * is only ever given two NAMES, so when it says "that's actually real" it is
 * telling us about a gap in the recipe graph rather than reciting from it.
 *
 * This turns that into a worklist. It is an authoring tool, run by hand: the
 * output goes nowhere near `src/`, and a candidate becomes a recipe only after
 * a human checks the transformation and finds a source, which is the same
 * rubric `scripts/propose.ts` has always had. The model proposes; it never
 * ships.
 */
import { writeFileSync } from 'node:fs'
import { GAME_DATA } from '../src/data/gameData'
import { PROPERTIES } from '../src/data/properties'

const ENDPOINT = 'https://from-scratch-three.vercel.app/api/adjudicate'
const LIMIT = Number(process.env.LIMIT ?? 140)

const byId = new Map(GAME_DATA.elements.map((e) => [e.id, e]))
const key = (a: string, b: string) => [a, b].sort().join('+')
const known = new Set(GAME_DATA.recipes.map((r) => key(r.inputs[0], r.inputs[1])))

/**
 * Skip the pairs the local rule table already answers confidently. There is no
 * point spending a call to be told two rocks do nothing; the interesting gaps
 * are where something could plausibly act on something else.
 */
function worthAsking(a: string, b: string): boolean {
  const pa = PROPERTIES[a]
  const pb = PROPERTIES[b]
  if (!pa || !pb) return false
  if (a === b) return false
  if (pa.kind === 'tool' && pb.kind === 'tool') return false
  if (pa.kind === 'energy' && pb.kind === 'energy') return false
  if (pa.stage === 'finished' && pb.stage === 'finished') return false
  if (pa.phase === 'gas' && pb.phase === 'gas') return false
  return true
}

const ids = GAME_DATA.elements.map((e) => e.id)
const candidates: [string, string][] = []
for (let i = 0; i < ids.length; i++) {
  for (let j = i + 1; j < ids.length; j++) {
    if (known.has(key(ids[i], ids[j]))) continue
    if (!worthAsking(ids[i], ids[j])) continue
    candidates.push([ids[i], ids[j]])
  }
}

// Deterministic spread rather than the first N, which would all be survival.
const step = Math.max(1, Math.floor(candidates.length / LIMIT))
const sample = candidates.filter((_, i) => i % step === 0).slice(0, LIMIT)

console.log(`${candidates.length} missing pairs worth asking about; sampling ${sample.length}`)

const real: string[] = []
const notReal: string[] = []

for (const [a, b] of sample) {
  const nameA = byId.get(a)!.name
  const nameB = byId.get(b)!.name
  try {
    const res = await fetch(ENDPOINT, {
      method: 'POST',
      headers: { 'content-type': 'application/json' },
      body: JSON.stringify({ a: nameA, b: nameB }),
    })
    const { message } = (await res.json()) as { message: string | null }
    if (!message) continue
    const line = `${a} + ${b}  ::  ${message}`
    if (/that'?s actually real/i.test(message)) {
      real.push(line)
      console.log(`  REAL  ${line}`)
    } else {
      notReal.push(line)
    }
  } catch {
    // A failed call is not a finding. Skip it.
  }
}

writeFileSync(
  'plan/candidates.md',
  [
    '# Missing recipes the adjudicator says are real',
    '',
    'Generated by `npm run probe`. **Nothing here is a recipe yet.** Each line',
    'needs the transformation checked and a source found before it goes into',
    '`gameData.ts` by hand.',
    '',
    `Sampled ${sample.length} of ${candidates.length} missing pairs. ${real.length} came back real.`,
    '',
    ...real.map((l) => `- ${l}`),
    '',
    '## Answered as not real',
    '',
    ...notReal.slice(0, 40).map((l) => `- ${l}`),
  ].join('\n'),
)
console.log(`\n${real.length} of ${sample.length} said real -> plan/candidates.md`)
